enabled: true
update_interval: 1
action:
  max_step: 0.2
  ema: 0.5
  lr_min: 1.0e-5
  lr_max: 1.0
cooldown: 5
features:
  - epoch
  - step_in_epoch
  - global_step
  - train_loss
  - val_loss
  - train_acc
  - val_acc
  - lr_current
  - train_loss_ema
  - ema_acc
  - d_loss
  - d_acc
  - grad_norm
  - update_ratio

controller_arch:
  hidden: 32
  max_step: 0.2
